"""Stable concepts used to normalize changing IRS return lines."""

CANONICAL_CONCEPTS = {
    "identity.entity_type": "Federal return/entity classification",
    "identity.tax_year": "Tax year represented by the return",
    "identity.naics": "Principal business activity or NAICS code",
    "income.gross_receipts": "Gross receipts or sales before returns/allowances",
    "income.returns_allowances": "Returns and allowances",
    "income.net_receipts": "Gross receipts less returns and allowances",
    "income.gross_profit": "Gross profit after cost of goods sold",
    "income.wages": "Wages, salaries, tips, and similar compensation",
    "income.adjusted_gross": "Adjusted gross income",
    "income.total": "Total income reported by the entity",
    "income.interest": "Taxable interest income",
    "income.dividends": "Dividend income",
    "income.rents": "Rental income",
    "income.capital_gain": "Net capital gain or loss",
    "cogs.total": "Cost of goods sold",
    "expense.compensation_officers": "Compensation of officers",
    "expense.wages": "Salaries and wages other than officer compensation",
    "expense.rent": "Rent or lease expense",
    "expense.interest": "Interest expense",
    "expense.depreciation": "Depreciation and amortization expense",
    "expense.taxes_licenses": "Taxes and licenses",
    "expense.other": "Other deductions or expenses",
    "expense.total": "Total deductions or expenses",
    "taxable_income.total": "Taxable income or ordinary business income",
    "tax.total": "Total income tax or tax liability",
    "tax.refund": "Refund claimed",
    "tax.amount_owed": "Amount owed with the return",
    "balance.cash": "Cash balance",
    "balance.receivables": "Accounts or notes receivable",
    "balance.inventory": "Inventory balance",
    "balance.fixed_assets_gross": "Gross depreciable assets",
    "balance.fixed_assets_accum_depr": "Accumulated depreciation",
    "balance.total_assets": "Total assets",
    "balance.accounts_payable": "Accounts payable",
    "balance.debt": "Interest-bearing debt",
    "balance.related_party_receivable": "Loans or receivables from owners/related parties",
    "balance.related_party_payable": "Loans or payables to owners/related parties",
    "balance.total_liabilities": "Total liabilities",
    "equity.total": "Capital, retained earnings, or net assets",
    "passthrough.distributions": "Distributions to owners or beneficiaries",
    "passthrough.k1_income": "Allocated Schedule K-1 income",
    "reconciliation.book_income": "Income or loss per books",
    "reconciliation.book_tax_difference": "Book-to-tax difference",
}
