"""Stable concepts used to normalize changing IRS return lines."""

CANONICAL_CONCEPTS = {
    "identity.entity_type": "Federal return/entity classification",
    "identity.tax_year": "Tax year represented by the return",
    "identity.naics": "Principal business activity or NAICS code",
    "income.gross_receipts": "Gross receipts or sales before returns/allowances",
    "income.returns_allowances": "Returns and allowances",
    "income.net_receipts": "Gross receipts less returns and allowances",
    "income.gross_profit": "Gross profit after cost of goods sold",
    "income.wages": "Wages, salaries, tips, and similar compensation",
    "income.adjusted_gross": "Adjusted gross income",
    "income.total": "Total income reported by the entity",
    "income.interest": "Taxable interest income",
    "income.dividends": "Dividend income",
    "income.rents": "Rental income",
    "income.rental_real_estate": "Net rental real estate income or loss",
    "income.other_rental": "Other net rental income or loss",
    "income.royalties": "Royalty income",
    "income.capital_gain": "Net capital gain or loss",
    "cogs.total": "Cost of goods sold",
    "expense.compensation_officers": "Compensation of officers",
    "expense.wages": "Salaries and wages other than officer compensation",
    "expense.rent": "Rent or lease expense",
    "expense.interest": "Interest expense",
    "expense.depreciation": "Depreciation and amortization expense",
    "expense.taxes_licenses": "Taxes and licenses",
    "expense.other": "Other deductions or expenses",
    "expense.total": "Total deductions or expenses",
    "taxable_income.total": "Taxable income or ordinary business income",
    "tax.total": "Total income tax or tax liability",
    "tax.refund": "Refund claimed",
    "tax.amount_owed": "Amount owed with the return",
    "balance.cash": "Cash balance",
    "balance.receivables": "Accounts or notes receivable",
    "balance.inventory": "Inventory balance",
    "balance.fixed_assets_gross": "Gross depreciable assets",
    "balance.fixed_assets_accum_depr": "Accumulated depreciation",
    "balance.total_assets": "Total assets",
    "balance.accounts_payable": "Accounts payable",
    "balance.debt": "Interest-bearing debt",
    "balance.related_party_receivable": "Loans or receivables from owners/related parties",
    "balance.related_party_payable": "Loans or payables to owners/related parties",
    "balance.total_liabilities": "Total liabilities",
    "equity.total": "Capital, retained earnings, or net assets",
    "passthrough.distributions": "Distributions to owners or beneficiaries",
    "passthrough.guaranteed_payments": "Guaranteed payments allocated to partners",
    "passthrough.self_employment": "Self-employment earnings allocated to partners",
    "passthrough.k1_income": "Allocated Schedule K-1 income",
    "reconciliation.book_income": "Income or loss per books",
    "reconciliation.book_tax_difference": "Book-to-tax difference",
    "activity.net_profit": "Net profit or loss from a separately identified activity",
    "activity.total_expenses": "Total expenses of a separately identified activity",
    "passthrough.ordinary_income": "Ordinary income allocated through Schedule K or K-1",
    "passthrough.interest": "Separately stated interest income",
    "passthrough.dividends": "Separately stated dividend income",
    "passthrough.capital_gain": "Separately stated capital gain or loss",
    "passthrough.section1231": "Section 1231 gain or loss",
    "passthrough.charitable": "Charitable contributions allocated to owners",
    "passthrough.capital_beginning": "Owner capital account at beginning of year",
    "passthrough.contributions": "Owner capital contributions",
    "passthrough.current_income": "Current-year increase or decrease to owner capital",
    "passthrough.capital_ending": "Owner capital account at end of year",
    "reconciliation.permanent_differences": "Permanent book-to-tax differences",
    "reconciliation.temporary_differences": "Temporary book-to-tax differences",
    "reconciliation.tax_income": "Income or loss reported for tax purposes",
}
